export const driverDashboardData = {
  driver: {
    initial: "Б",
    name: "Болд Батаа",
    phone: "+976 9911 2233",
    email: "bold@example.com",
    status: "Идэвхтэй",
    rating: "4.9",
    reviewCount: 48,
    trips: 120,
    monthlyIncome: "₮820K",
    todayIncome: "₮180K",
    acceptanceRate: "96%",
    onTimeRate: "98%",
    license: {
      number: "MN-12345678",
      class: "B ангилал",
      expiry: "2028-09-12",
      experience: "8 жил",
    },
  },
  activeBooking: {
    car: "Toyota Alphard",
    route: "Хөвсгөл нуур",
    customer: "Сарантуяа Б",
    date: "3/20 → 3/23",
    destination: "УБ → Мөрөн",
    duration: "3 хоног",
    amount: "₮540,000",
    progress: "65%",
    remaining: "1 өдөр үлдсэн",
  },
  requests: [
    {
      id: "req1",
      title: "Alphard — Тэрэлж",
      customer: "Ганбаатар О",
      date: "3/25 → 3/27",
      amount: "₮360,000",
      days: "2 өдөр",
      details: ["📍 УБ → Тэрэлж", "👥 3 хүн", "⏰ 08:00 эхлэх"],
    },
    {
      id: "req2",
      title: "Alphard — Булган",
      customer: "Энхтуяа Д",
      date: "3/28 → 3/31",
      amount: "₮540,000",
      days: "3 өдөр",
      details: ["📍 УБ → Булган", "👥 5 хүн", "⏰ 07:00 эхлэх"],
    },
  ],
  history: [
    {
      title: "Хөвсгөл нуур · 3 хоног",
      meta: "Сарантуяа Б · 3/17 – 3/20",
      amount: "₮540,000",
      status: "Дууссан",
      tone: "done",
    },
    {
      title: "Горхи-Тэрэлж · 1 хоног",
      meta: "Бямбасүрэн Г · 3/14",
      amount: "₮180,000",
      status: "Дууссан",
      tone: "done",
    },
    {
      title: "Дархан хот · 2 хоног",
      meta: "Мөнхбат О · 3/10 – 3/12",
      amount: "₮360,000",
      status: "Дууссан",
      tone: "done",
    },
  ],
  earnings: [
    { label: "Да", height: "40%", current: false },
    { label: "Мя", height: "65%", current: false },
    { label: "Лх", height: "30%", current: false },
    { label: "Пү", height: "80%", current: false },
    { label: "Ба", height: "55%", current: false },
    { label: "Бя", height: "20%", current: false },
    { label: "Ня", height: "90%", current: true },
  ],
  car: {
    name: "Toyota Alphard 2022",
    meta: "Цагаан · 1234 УНА · 7 суудал",
    status: "● Ашиглалтад",
  },
} as const;
